enabledWorlds: [world, world_nether, world_the_end]
BuySlot GUI Name: "Inventory Upgrade"
#This is in case they somehow get an item in a locked slot, it won't delete the item.
deleteItemsInSlots: false
#This allows a user to move the fill item in their inventory while in creative. (Recommended)
allowClickInCreative: true
#How often it sets the fill item in an inventory (Seconds)
Timer Interval: 10
GUIItemNames:
    CloseMenu: "&eClose Menu"
    Purchase: "&aPurchase New Slot"
    Unlocked: "&7Unlocked"
FillItem:
    fillItemMaterial: RED_STAINED_GLASS_PANE
    qty: 1
    #Prefered to keep this not blank. Might cause a bug with other plugins
    name: "&cLocked"
    
messages:
    Error: "&cThere was an error. Please contact an Admin"
    NotPlayer: "&cOnly players can use this command"
    NotEnoughMoney: "&cYou do not have enough money for this purchase."
    NoPerm: "&cYou do not have the permission %perm%!"
    SuccessfulPurchase: "&aYou just bought a new slot!"
UpgradeCost:
    2: 2000
    3: 3000
    4: 4000
    5: 5000
    6: 6000
    7: 7000
    8: 8000
    9: 9000
    10: 10000
    11: 11000
    12: 12000
    13: 13000
    14: 14000
    15: 15000
    16: 16000
    17: 17000
    18: 18000
    19: 19000
    20: 20000
    21: 21000
    22: 23000
    24: 24000
    25: 25000
    26: 26000
    27: 27000 